import header from './header';
import navDrawer from './nav-drawer';
import mobileNavDropdowns from './mobile-nav-dropdowns';
import heroSlider from './hero-slider';
import gallerySlider from './gallery-slider';
import productSinglePage from './page-product-single';
import resourcesPage from './page-resources';
import gallery from './gallery';
import categoryList from './category-list';
import findADealer from './find-a-dealer';
import search from './search';
import lazyloading from './lazyloading';
import './components';
import './ui';
import './cart-sidebar';

import './shopify/main';

header();
navDrawer();
mobileNavDropdowns();
heroSlider();
gallerySlider();
productSinglePage();
resourcesPage();
gallery();
categoryList();
findADealer();
search();
lazyloading();
